# Generated by Django 4.2 on 2025-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendingmachine',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendingmachine',
            name='payback_period',
            field=models.IntegerField(default=0),
        ),
    ]
